version: '3'
services:
  app:
    container_name: sys_backend
    build: 
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./app/${APP_NAME}:/src
    ports:
      - "${APP_PORT:-8000}:8000"

